### ISSUE TITLE
각 레벨/알고리즘 클릭 시, 1개의 문제가 화면에 표시

### ISSUE THREAD

**Issue by w36495** [w36495/randomrithm#7]
## Todo
- [ ] 알고리즘 클릭 시, 해당 알고리즘 관련 문제 목록 가져오기
- [ ] 레벨 클릭 시, 해당 알고리즘 관련 문제 목록 가져오기
- [ ] 문제 목록 중 1개의 문제 화면에 보이기
- [ ] '다음 문제 받기' 버튼 클릭 -> 기존의 레벨(or 알고리즘) 문제 목록 중 다른 문제 1개 보이기
